<a href="https://colab.research.google.com/github/AmitPress/google-colab/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


[Guide Link](https://www.python-engineer.com/posts/numpy-crash-course/)

In [2]:
import numpy as np

In [3]:
np.__version__

'1.21.6'

In [4]:
# central object is the array
a = np.array([[1, 2, 1],
              [2, 1, 6]])
print(a.shape) # shape is of (rows, cols)
print(a.size) # total number of element
# observation
# 1D array elements signifies rows (a vector basically)
# 2D array elements signifies cols (a tensor basically)

print(a.dtype)

(2, 3)
6
int64


In [5]:
# list operations
l = [1, 2, 3]

# element wise
# add, sub, mul, div
# broadcasted addition is not possible
# l2 = l + 6 #gives error
# l2
# broadcasted addition is not possible
# l3 = l - 3 # error
# l3
# multiplication
# l4 = l * 2 
# l4 # [1, 2, 3, 1, 2, 3]
# division 
# l5 = l / 2
# l5 # error
# verdict: in a list addition, subtraction and division is not possible in element wise mannar

# list wise
# addition is concatenation
l1 = l + [6, 9]
# subtraction
# l12 = l - [1]
# l12 # not possible
# mul
# l23 = l * [2]
# l23 # not possible
# div
# l34 = l * [7]
# l34 # not possible


In [6]:
# numpy array operations
# broadcasting is supported

ar = np.array([[1, 2],
               [2, 1]])
# addition
ar + 5
# subtraction
ar - 5
# multiplication
ar * 5
# division
ar / 5
# division by zero
ar / 0 # inf
# division by inf
ar / np.inf # 0

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:15: RuntimeWarning: divide by zero encountered in true_divide
  from ipykernel import kernelapp as app


array([[0., 0.],
       [0., 0.]])

In [7]:
# np.array operator np.array
x = np.array([[1, 2],
             [2, 1]])

y = np.array([[0, 1],
             [1, 0]])
# add
x + y
# sub
x - y
# matmul
x * y
# matdiv
x / y

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:14: RuntimeWarning: divide by zero encountered in true_divide
  


array([[inf,  2.],
       [ 2., inf]])

In [8]:
u = np.array([1, 2, 1])
v = np.array([5, 5, 5])
# dot 1
u.dot(v)
# dot 2
(u * v).sum()
# dot 3
u @ v

20

Transpose

In [9]:
O = np.array([[-1, -2, -1],
             [ 0,  0,  0],
             [ 1,  2,  1]])
O.T

array([[-1,  0,  1],
       [-2,  0,  2],
       [-1,  0,  1]])

np.linalg

In [10]:
j = np.array([[1, 2, 3],
              [8, 1, 7],
              [3, 8, 3]])
np.linalg.det(j)
np.linalg.inv(j)

array([[-0.42741935,  0.14516129,  0.08870968],
       [-0.02419355, -0.0483871 ,  0.13709677],
       [ 0.49193548, -0.01612903, -0.12096774]])

In [16]:
# zeros
z = np.zeros((3, 2))
o = np.ones((2, 2))
e = np.eye(3)
e

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
# arange and reshape

ar = np.arange(10)
ar.reshape((5, 2)) # eta bhala na :3

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])